### ISSUE TITLE
Fishing minigame

### ISSUE THREAD

**Issue by Krazzy11** [vncsms/Metin2FishBot#14]
Hi, I trying to get contact you on discord and on mail, but no response.
So first, thanks for making this fishbot and good work.
There is a minigame where you need to click on the fish in specified location ( circle) and I don't see working on your project.
I will attached some photos about the minigame, I hope you will answer.
Have a nice day.
![image](https://github.com/vncsms/Metin2FishBot/assets/107494530/51b85625-92a7-4103-83e4-a3be0ef9d037)

**Comment by vncsms** [comment]
Hello, you can first try to check those three possible problems:

- Check the windows name: The bot look for the windows (Game client) name. Mine is metin2, some people play in diferent servers.
- Check if you are running the bot as admin. The game doesnt have permisson to click in the game.
- Some servers set this windows (Fishing mechanic) in diferrent positions. My bot doesnt track this window whatever it is. You need to configure in case you server is different.

**Comment by Krazzy11** [comment]
Hi, thanks for reply, I did the first 2 problems, bot is using the bait and pressing the spacebar, but not clicking on the fish, what I really want to say if this minigame is implemented on your bot?
On the third problem you mention, I really don't know how to do it :(

**Comment by Krazzy11** [comment]
And another thing is about when I am pressing the "START" on the puzzle window nothing happens.
![image](https://github.com/vncsms/Metin2FishBot/assets/107494530/cc889c7c-8bc4-421d-a012-b5e1878f92aa)

**Comment by vncsms** [comment]
The minigame is implemented.
- The minigame is the first tab. The second tab is the tetris puzzle game.
-  Where is located the minigame when it stars? Where is the game spawned on the window?

**Comment by Krazzy11** [comment]
![image](https://github.com/vncsms/Metin2FishBot/assets/107494530/350c5d76-0215-4f4b-94d5-be320a34c4cb)

In the top left corner
