### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by giovanijb** [vncsms/Metin2FishBot#15]
I'm following the installation tutorial to do tests, but when running the command: virtualenv metin2, the return is that virtualenv is not a recognized command. How to proceed?

**Comment by vncsms** [comment]
Hello, did you run `pip install virtualenv`?

**Comment by giovanijb** [comment]
Sorry for the topic, the python version was different and I don't know why this problem occurred. Python is new to me, I only program in Java, but it worked now.

**Comment by vncsms** [comment]
No problem.
