### ISSUE TITLE
Bot closing by itself

### ISSUE THREAD

**Issue by giovanijb** [vncsms/Metin2FishBot#16]
Efetuei todos os procedimentos conforme o vídeo, alterei também o nome do game para que fique igual ao que estou usando, entretanto, ao clicar em START o BOT se fecha sozinho. O que posso fazer?

**Comment by vncsms** [comment]
Como que você executou o bot, foi gerando o executavel ou pelo terminal?

**Comment by giovanijb** [comment]
Through the executable, which generates in the dist folder

**Comment by giovanijb** [comment]
![Capturar](https://github.com/vncsms/Metin2FishBot/assets/53920596/29c82aac-3ff2-44ed-b71e-1e8a6ad228fe)

**Comment by vncsms** [comment]
Can you print the game's name?

**Comment by giovanijb** [comment]
Problema em questão foi resolvido.
