### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Ryr0** [vncsms/Metin2FishBot#17]
bot not working, it instantly closes, changing name in constants.py does nothing, i tried to put evey name possible in that file and the console stills says METIN2
![Screenshot_8](https://github.com/vncsms/Metin2FishBot/assets/29474802/9776c068-659c-44be-a1cd-f88452a9cd05)
![Screenshot_9](https://github.com/vncsms/Metin2FishBot/assets/29474802/2d6d426f-d7ff-4e56-b6e7-a6eca1372b11)

**Comment by vncsms** [comment]
Did you change the name before generating the executable?

When you change the executable, what is in the .py files doesnt matter anymore.

**Comment by Ryr0** [comment]
i did it all again and now it's not closing instantly, it does use the bait and initiate the fishing but doesn't click anywhere. do you have any clue about that? i am starting it as admin, and i did not move the window.
thanks for your time

**Comment by vncsms** [comment]
It seems some servers change the window position to avoid the bot #12 see this post. The solution is to change where the code is trying to find the window.

**Comment by Ryr0** [comment]
what pixel do i select here to start measuring? where does the fishing widow start for the bot?
![Screenshot_13](https://github.com/vncsms/Metin2FishBot/assets/29474802/76677563-25ce-4844-a13b-2c03fb3e4095)
i fiddled with it a little and i think i'm close, but i still don't know where to put my starter point so it still a little off
![Screenshot_14](https://github.com/vncsms/Metin2FishBot/assets/29474802/041562ea-baf3-482a-b0a0-b12351ed7428)

**Comment by vncsms** [comment]
![image](https://github.com/vncsms/Metin2FishBot/assets/12662329/a3ffe04b-e979-4156-b703-a4fccfce2e42)

Mine is like that

**Comment by vncsms** [comment]
I see, maybe the servers are trying to change the colors and the size to avoid my bot. This is not hard to fix, but you need to experiment changing the values and underrstand what is happening in the code.
