### ISSUE TITLE
fish filter

### ISSUE THREAD

**Issue by jpitimarin** [vncsms/Metin2FishBot#18]
Hello, does the fish filter work? I have tried to activate it, but it does not work correctly, I have created a function to filter the names of the fish, I know that sometimes the name does not come out correctly, but some parts of the names always match and I want to use those parts to use them as a filter.

**Comment by vncsms** [comment]
This filter is not working properly.  You chan check the version https://github.com/vncsms/Metin2FishBot/tree/v2.0
The readme shows how to activate the filter, works in the latest version as well.

**Comment by vncsms** [comment]
Question answered
