### ISSUE TITLE
Black capture Screen

### ISSUE THREAD

**Issue by giovanijb** [vncsms/Metin2FishBot#19]
In a new game update, when starting fishing the capture screen for the software is all black, but visually it is possible to see. how can we get around this?

**Comment by vncsms** [comment]
Can you show me the capture screen. Maybe you metin2 server changed the minigame of position.

**Comment by giovanijb** [comment]
When using fishing, the game uses a resource that is visible to the player, but when trying to capture or record the screen, the game screen is all black.

**Comment by giovanijb** [comment]
https://github.com/vncsms/Metin2FishBot/assets/53920596/78080e23-606a-45c2-aa74-401f719139a8

**Comment by vncsms** [comment]
I do not understand the problem.

**Comment by giovanijb** [comment]
When loading the fishing screen, the game disables the image for the software that reads the screen, thus turning it black. But it keeps it active for whoever is viewing it on the monitor.

**Comment by vncsms** [comment]
I couldn't solve the problem.
