### ISSUE TITLE
Bot is closing after starting fishing on WoM2, please fix

### ISSUE THREAD

**Issue by blueiron96** [vncsms/Metin2FishBot#26]
Hello, i have an issue with bot on World of Metin2 (WoM2). After start bot, it press bait and start fishing, when the fishing screen appear, the bot is closing. I attached a photo with fishing system. It has to be a solution to bypass that.
Please fix it or help me to bypass that.
Best regards, Thank You!
![1020_143033](https://github.com/vncsms/Metin2FishBot/assets/148548170/fa742070-7bbd-452a-b067-d8c57d0afeff)

**Comment by ghost** [comment]
@vncsms So what is the problem with wom2, from what I noticed when you film the screen and the fishing minigame appears, in the video that sequence the screen is black, and I think that's why the algorithm shuts down, because it can't visualize the movements, can you solve it somehow this problem?

**Comment by vncsms** [comment]
The game is blocking softwares to capture the screen. You can check by yourself. Try to record your game while fishing. All the software can see is a black screen. I coulnd´t find a solution for this problem.

**Comment by K011L** [comment]
did they fix it?

**Comment by K011L** [comment]
how did you add the fish skill?
