### ISSUE TITLE
Daily event

### ISSUE THREAD

**Issue by KozbialP** [vncsms/Metin2FishBot#39]
Hi,
What should I change in code in order to choose always first option in daily event?

**Comment by vncsms** [comment]
Line 196 in the file  fishingbot.py

You need to calculate the exact position, and then just change the numbers.

```
        if daily:
            mouse_x = int(self.wincap.offset_x + 350)
            mouse_y = int(self.wincap.offset_y + 280)
            pydirectinput.click(x=mouse_x, y=mouse_y)
```

**Comment by KozbialP** [comment]
Ok, thank you for help
