### ISSUE TITLE
It doesnt play the minigame

### ISSUE THREAD

**Issue by TheOneLeeT** [vncsms/Metin2FishBot#4]
It only put bait and throw it in water, and will pick up after X seconds (Wich is setted up in Option tab) But without playing the minigame to actually 'catch' the fish.

**Comment by vncsms** [comment]
Can you check with the resolution of the game is 800 x 600 and the bot is running in adm mode?

**Comment by ervindobri** [comment]
Can confirm, I tried and it's not working. Just putting bait and throwing the fishing rod in, then pulling it out.

**Comment by vncsms** [comment]
-

> Can confirm, I tried and it's not working. Just putting bait and throwing the fishing rod in, then pulling it out.

Can you add me in discord to check that?
