### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by SinoX1337** [vncsms/Metin2FishBot#40]
Can u explain me what i need to do if i have a Fish window thats in the middle of the screen.

What i need to do with FISH_WINDOW_SIZE and  FISH_WINDOW_POSITION

Can u please help me to understand what i need to do to get it fully working :D

U can also write me on Discord when u want .sinox1337

Thanks

**Comment by vncsms** [comment]
The FISH_WINDOW_SIZE will not change, it's just the window size.
The FISH_WINDOW_POSITION is the position of the window on the screen. Yes, if the game changed the initial position you need to change the position.

**Comment by SinoX1337** [comment]
Okay nice thanks :D

Is there a way to add Strg + G after the fishgame is closing to skip the animation?
