### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by Tothale** [vncsms/Metin2FishBot#7]
Hi. Tab is coming but when i click to start, i get this error:

Traceback (most recent call last):
  File "hack.py", line 27, in <module>
  File "fishingbot.py", line 235, in runHack
  File "fishingbot.py", line 137, in detect_minigame
cv2.error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:1104: error: (-215:Assertion failed) (depth == CV_8U || depth == CV_32F) && type == _templ.type() && _img.dims() <= 2 in function 'cv::matchTemplate'

[11064] Failed to execute script hack

**Comment by vncsms** [comment]
Make sure that your python version is 3.8 or higher. What your python version?

**Comment by Tothale** [comment]
I've tried on python 3.8.5 and 3.9.7 it didn't worked.

**Comment by Tothale** [comment]
Finally i found my mistake. I forgot to transfer the exe in the dist folder to main folder.
