### ISSUE TITLE
Pydirectinput does not work?

### ISSUE THREAD

**Issue by hrabosh** [vncsms/Metin2FishBot#8]
Hello, I tried to setup it up and it looks great but I think pydirectinput does not work. It does not add bait to rod and even not throw the bait. I also tried to pydirenctinput.keyDown('esc') as a test if the menu will be opened and nothing happened. Can you help me please?

**Comment by vncsms** [comment]
Can you check if the execution is running as admin? Because the only way to the bot send a command to the game is if is running as admin.

**Comment by hrabosh** [comment]
Yes, I run it as administrator and in task manager it has elevated attribute. I recorded short video, link here https://youtu.be/84pPn8q3lKE

**Comment by vncsms** [comment]
What is the name of your game? That shows on the window.

**Comment by hrabosh** [comment]
METIN2 same as in constants.py - It is official metin2 server. Now I have this error in console 
![error](https://user-images.githubusercontent.com/15844896/150544766-b736b15c-ddf4-4216-a910-8d9866968df4.PNG)

**Comment by vncsms** [comment]
Did you move the exe from dist folder to the main folder?

**Comment by hrabosh** [comment]
My god. I am so sorry. Now I have read the last sentence of the manual `When it's end move the executable file in the folder dist to the project's root.` Sorry and thank you for help. Really great job

**Comment by vncsms** [comment]
Did work?

**Comment by hrabosh** [comment]
Yes, it works on official metin2 server. Now I will try to run it on a private server but I have to modify the code a bit because fishing window has different coordinations. The second problem is that on the private server the timing between opening fishing windows is different. Also on the private server sometimes there must be 3 click on fish, sometimes 6 clicks on fish and sometimes 5 clicks on fish. So I have to modify the code to work properly on the private server

**Comment by vncsms** [comment]
Nice.
