### ISSUE TITLE
jigsaw too slow

### ISSUE THREAD

**Issue by Feyzz01** [vncsms/Metin2FishBot#9]
It takes time to go up and down each piece. Why don't you decide right away? it's so slow

**Comment by vncsms** [comment]
Sry, I didn't understand. It takes some time for the code to decide which place the piece must be, but it's fast. In slow computers, the bot can be slower. If that is not the case, maybe you can reduce the wait time on the code, but it's already only 0.2 seconds. If you still have this problem you can add me on discord, we can try to find a solution.

**Comment by Feyzz01** [comment]
Let's talk on discord. please write your username.  Me : Adana4343 #3813

31 Ağu 2022 Çar 16:00 tarihinde Vinícius Morais Silva <
***@***.***> şunu yazdı:

**Comment by vncsms** [comment]
picicio#4827

**Comment by stefanlnt23** [comment]
It opens but when i press start i get this error, note i changed the window name from Metin2 to my window name, but dont think this is the problem anyway

![image](https://user-images.githubusercontent.com/80775523/229337751-de315f75-1c18-42cf-90bf-bd499d393590.png)

**Comment by vncsms** [comment]
> It opens but when i press start i get this error, note i changed the window name from Metin2 to my window name, but dont think this is the problem anyway
> 
> ![image](https://user-images.githubusercontent.com/80775523/229337751-de315f75-1c18-42cf-90bf-bd499d393590.png)

I updated the code and the required versions. Try to use python 3.11 now.
